name: Bug report
description: Report a bug in Inrupt Java Client Libraries
labels: bug
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: >-
        Describe the issue you are experiencing here to communicate to the
        maintainers. Tell us what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is.
  - type: textarea
    attributes:
      label: Expected behavior
      description: >-
        Describe the expected behavior clearly and concisely.
  - type: textarea
    attributes:
      label: Actual behavior
      description: >-
        Describe the actual behavior clearly and concisely.
  - type: textarea
    attributes:
      label: How to reproduce?
      description: >-
        Link to a small reproducer (preferably a Maven project in a public git repository) or attach an archive containing the reproducer to the issue.
      placeholder: |
        Reproducer:

        Steps to reproduce the behavior:
        1. 
        2. 
        3.        
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: textarea
    attributes:
      label:  Output of `java -version`
  - type: input
    attributes:
      label:  Maven version
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
