name: Feature request / Enhancement
description: Request or propose a new feature/enhancement
labels: enhancement
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Feature/enhancement description
      description: >-
        Describe the feature/enhancement here.
  - type: textarea
    attributes:
      label: Expected result
      description: >-
        If the idea diverges from how it is now implemented, please describe the differences.
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
