logging:
  level:
    root: info
spring:
  main:
    banner-mode: "off"
  security:
    oidc:
      post-logout-redirect-uri: http://localhost:8080/
      signature-algorithm: ES256
    oauth2:
      client:
        registration:
          myApp:
            client-id: https://inrupt.github.io/solid-client-java/clients/springboot-testing.jsonld
            provider: inrupt
            scope:
              - openid
              - webid
            client-authentication-method: none
            authorization-grant-type: authorization_code
        provider:
          inrupt:
            issuer-uri: https://login.inrupt.com
