name: Solid Java Client Dependencies

on:
  # Build pull requests for any branch
  pull_request: { }

jobs:
  dependencies:
    name: Java environment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17 ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Build the code with Maven
        run: mvn -B -ntp clean verify -Pdependencies

